#!/usr/bin/env node
var seed = 1

var fs = require('fs');
eval(fs.readFileSync('../js/questions/pythonProgramOutput.js')+'');
eval(fs.readFileSync('../js/bits.js')+'');
eval(fs.readFileSync('../js/random.js')+'');


var randomStream = new RandomStream(seed);
var questionFunc = pythonProgramOutput;
var questions = new questionFunc(randomStream)
console.log(questions.formatAnswer("HTML"))
console.log(questions.formatQuestion("HTML"))

